"""add_new_recording_status_enum_values

Revision ID: 1caadece39ca
Revises: e777938b85cc
Create Date: 2025-05-30 16:40:57.278795

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '1caadece39ca'
down_revision: Union[str, None] = 'e777938b85cc'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_analysis_history_recording_id_type'), table_name='analysis_history')
    
    # 注意：状态字段目前是 VARCHAR，所以新的状态值已经可以使用
    # 不需要修改数据库架构，只需要应用程序代码支持新值即可
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index(op.f('ix_analysis_history_recording_id_type'), 'analysis_history', ['recording_id', 'analysis_type'], unique=False)
    # ### end Alembic commands ###
